all:
  children:
    managers:
      hosts:
        spark-1:
          ansible_host: 192.168.255.2
          cx7_ip: 10.10.10.1
          nfs_export_dir: /data/shared1
          nfs_mount_from: 10.10.10.2:/data/shared2
          nfs_mount_to: /data/shared2
          desired_hostname: spark-1
    workers:
      hosts:
        spark-2:
          ansible_host: 192.168.255.3
          cx7_ip: 10.10.10.2
          nfs_export_dir: /data/shared2
          nfs_mount_from: 10.10.10.1:/data/shared1
          nfs_mount_to: /data/shared1
          desired_hostname: spark-2
  vars:
    ansible_user: user
    ansible_become: true
    # ansible_become_pass: use --ask-become-pass or ansible-vault
    ansible_python_interpreter: /usr/bin/python3

    mgmt_interface: enP7s7

    cx7_interfaces:
      - enp1s0f0np0
      - enp1s0f1np1
      - enP2p1s0f0np0
      - enP2p1s0f1np1
    bond_name: bond0
    cx7_bond_subnet: "10.10.10.0/30"
    cx7_bond_mode: balance-xor

    wifi_interface: wlP9s9
    disable_wifi: true

    bridge_names:
      - br-containers
      - br-vms

    nfs_threads: 32
    nfs_opts: "rw,async,no_subtree_check,no_root_squash"

    slurm_partition_name: gpu
    data_dir: /data
    install_dir: /opt/spark-manager
